using System.Globalization;
using System.Reflection;
using System.Text;
using Boutique.Models;
using Boutique.ViewModels;

namespace Boutique.Utilities;

/// <summary>
///   Central formatter for distribution file content.
///   This is the single source of truth for SPID and SkyPatcher file format generation.
/// </summary>
public static class DistributionFileFormatter
{
  public static void AppendSpidFilterPositions(StringBuilder sb, params string?[] parts)
  {
    var lastNonNullIndex = Array.FindLastIndex(parts, p => p != null);
    for (var i = 0; i <= lastNonNullIndex; i++)
    {
      sb.Append('|');
      sb.Append(parts[i] ?? "NONE");
    }
  }

  /// <summary>
  ///   Gets the application version from the assembly's informational version (set by MinVer from git tags).
  /// </summary>
  public static string GetAppVersion()
  {
    var assembly    = Assembly.GetExecutingAssembly();
    var infoVersion = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;

    if (!string.IsNullOrEmpty(infoVersion))
    {
      var plusIndex = infoVersion.IndexOf('+');
      return plusIndex > 0 ? infoVersion[..plusIndex] : infoVersion;
    }

    var version = assembly.GetName().Version;
    return version != null ? $"{version.Major}.{version.Minor}.{version.Build}" : "0.0.0";
  }

  /// <summary>
  ///   Generates the standard header lines for distribution files.
  /// </summary>
  public static List<string> GenerateHeaderLines(string? fileTypePrefix = null)
  {
    var version = GetAppVersion();
    var date    = DateTime.Now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
    var prefix  = string.IsNullOrEmpty(fileTypePrefix) ? string.Empty : $"{fileTypePrefix} ";

    return
    [
      $"; {prefix}Distribution File",
      $"; Generated by Boutique: {version}",
      $"; Last Modified: {date}",
      string.Empty
    ];
  }

  /// <summary>
  ///   Generates the complete file content for a distribution file.
  /// </summary>
  public static string GenerateFileContent(
    IEnumerable<DistributionEntryViewModel> entries,
    DistributionFileType format,
    IReadOnlyList<DistributionParseError>? unparsedLines = null)
  {
    var lines = GenerateHeaderLines();

    foreach (var entry in entries)
    {
      string? line = null;

      if (entry.Type == DistributionType.Keyword)
      {
        if (!string.IsNullOrWhiteSpace(entry.KeywordToDistribute))
        {
          line = FormatSpidKeywordLine(entry);
        }
      }
      else if (entry.Type == DistributionType.ExclusiveGroup)
      {
        if (!string.IsNullOrWhiteSpace(entry.ExclusiveGroupName) &&
            !string.IsNullOrWhiteSpace(entry.ExclusiveGroupFormsText))
        {
          line = FormatSpidExclusiveGroupLine(entry);
        }
      }
      else if (entry.SelectedOutfit != null)
      {
        line = format == DistributionFileType.Spid
                 ? FormatSpidLine(entry)
                 : FormatSkyPatcherLine(entry);
      }

      if (line != null)
      {
        lines.Add(line);
      }
    }

    if (unparsedLines is not { Count: > 0 })
    {
      return string.Join(Environment.NewLine, lines);
    }

    var spidPreserved = unparsedLines.Where(e =>
                                              e.Reason.EndsWith("(preserved)", StringComparison.Ordinal) &&
                                              e.Reason.Contains("SPID", StringComparison.OrdinalIgnoreCase)).ToList();
    var skyPatcherPreserved = unparsedLines.Where(e =>
                                                    e.Reason.EndsWith("(preserved)", StringComparison.Ordinal) &&
                                                    e.Reason.Contains("SkyPatcher", StringComparison.OrdinalIgnoreCase))
                                           .ToList();
    var errorLines = unparsedLines.Where(e => !e.Reason.EndsWith("(preserved)", StringComparison.Ordinal)).ToList();

    if (spidPreserved.Count > 0)
    {
      lines.Add(string.Empty);
      lines.Add("; Other SPID distributions (preserved from original file)");
      lines.AddRange(spidPreserved.Select(preserved => preserved.LineContent));
    }

    if (skyPatcherPreserved.Count > 0)
    {
      lines.Add(string.Empty);
      lines.Add("; SkyPatcher distributions with unresolved filters (preserved from original file)");
      lines.AddRange(skyPatcherPreserved.Select(preserved => preserved.LineContent));
    }

    if (errorLines.Count <= 0)
    {
      return string.Join(Environment.NewLine, lines);
    }

    lines.Add(string.Empty);
    lines.Add("; Lines that Boutique could not parse (preserved from original file)");
    lines.AddRange(errorLines.Select(error => error.LineContent));

    return string.Join(Environment.NewLine, lines);
  }

  /// <summary>
  ///   Formats a single entry as a SPID distribution line.
  ///   Format: Outfit = FormID|StringFilters|FormFilters|LevelFilters|TraitFilters|Count|Chance
  /// </summary>
  public static string FormatSpidLine(DistributionEntryViewModel entry)
  {
    if (entry.SelectedOutfit == null)
    {
      throw new ArgumentException("Entry must have a selected outfit", nameof(entry));
    }

    var outfitIdentifier = FormKeyHelper.FormatForSpid(entry.SelectedOutfit.FormKey);
    return BuildSpidLine("Outfit", outfitIdentifier, entry);
  }

  /// <summary>
  ///   Formats a single entry as a SPID keyword distribution line.
  ///   Format: Keyword = EditorID|StringFilters|FormFilters|LevelFilters|TraitFilters|Count|Chance
  /// </summary>
  private static string FormatSpidKeywordLine(DistributionEntryViewModel entry)
  {
    if (string.IsNullOrWhiteSpace(entry.KeywordToDistribute))
    {
      throw new ArgumentException("Entry must have a keyword to distribute", nameof(entry));
    }

    return BuildSpidLine("Keyword", entry.KeywordToDistribute, entry);
  }

  /// <summary>
  ///   Formats a single entry as a SPID exclusive-group line.
  ///   Format: ExclusiveGroup = GroupName|FormsList
  /// </summary>
  public static string FormatSpidExclusiveGroupLine(DistributionEntryViewModel entry)
  {
    if (string.IsNullOrWhiteSpace(entry.ExclusiveGroupName))
    {
      throw new ArgumentException("Entry must have an exclusive-group name", nameof(entry));
    }

    if (string.IsNullOrWhiteSpace(entry.ExclusiveGroupFormsText))
    {
      throw new ArgumentException("Entry must have exclusive-group forms", nameof(entry));
    }

    return $"ExclusiveGroup = {entry.ExclusiveGroupName}|{entry.ExclusiveGroupFormsText}";
  }

  private static string BuildSpidLine(string formType, string identifier, DistributionEntryViewModel entry)
  {
    var (stringFiltersPart, formFiltersPart) = BuildSpidFilterParts(entry);
    var           levelFiltersPart = !string.IsNullOrWhiteSpace(entry.LevelFilters) ? entry.LevelFilters : null;
    var           traitFiltersPart = FormatTraitFilters(entry.Entry.TraitFilters);
    const string? countPart        = null;
    var chancePart = entry.UseChance && entry.Chance != 100
                       ? entry.Chance.ToString(CultureInfo.InvariantCulture)
                       : null;

    var sb = new StringBuilder();
    sb.Append(formType)
      .Append(" = ")
      .Append(identifier);

    AppendSpidFilterPositions(
      sb,
      stringFiltersPart,
      formFiltersPart,
      levelFiltersPart,
      traitFiltersPart,
      countPart,
      chancePart);

    return sb.ToString();
  }

  private static (string? StringFilters, string? FormFilters) BuildSpidFilterParts(DistributionEntryViewModel entry) =>
    (BuildStringFiltersPart(entry), BuildFormFiltersPart(entry));

  private static string? BuildStringFiltersPart(DistributionEntryViewModel entry)
  {
    var parts = new List<string>();

    var includedNpcNames = entry.SelectedNpcs
                                .Where(npc => !npc.IsExcluded && !string.IsNullOrWhiteSpace(npc.DisplayName))
                                .Select(npc => npc.DisplayName)
                                .ToList();
    if (includedNpcNames.Count > 0)
    {
      var separator = entry.NpcLogicMode == FilterLogicMode.Or ? "," : "+";
      parts.Add(string.Join(separator, includedNpcNames));
    }

    var includedKeywords = entry.SelectedKeywords
                                .Where(k => !k.IsExcluded && !string.IsNullOrWhiteSpace(k.EditorID) &&
                                            k.EditorID != "(No EditorID)")
                                .Select(k => k.EditorID)
                                .ToList();
    if (includedKeywords.Count > 0)
    {
      var separator = entry.KeywordLogicMode == FilterLogicMode.Or ? "," : "+";
      parts.Add(string.Join(separator, includedKeywords));
    }

    parts.AddRange(
      entry.SelectedKeywords
           .Where(k => k.IsExcluded && !string.IsNullOrWhiteSpace(k.EditorID) && k.EditorID != "(No EditorID)")
           .Select(k => $"-{k.EditorID}"));

    if (!string.IsNullOrWhiteSpace(entry.RawStringFilters))
    {
      parts.Add(entry.RawStringFilters.Trim());
    }

    return parts.Count > 0 ? string.Join(",", parts) : null;
  }

  private static string? BuildFormFiltersPart(DistributionEntryViewModel entry)
  {
    var terms      = new List<List<string>>();
    var exclusions = new List<string>();

    CollectEditorIdFilters(entry.SelectedFactions, entry.FactionLogicMode, terms, exclusions);
    CollectEditorIdFilters(entry.SelectedRaces, entry.RaceLogicMode, terms, exclusions);

    AddFormFilterTerm(
      entry.SelectedClasses
           .Where(c => !string.IsNullOrWhiteSpace(c.EditorID) && c.EditorID != "(No EditorID)")
           .Select(c => c.EditorID!)
           .ToList(),
      entry.ClassLogicMode,
      terms);

    AddFormFilterTerm(
      entry.SelectedLocations
           .Select(loc => FormKeyHelper.FormatForSpid(loc.FormKey))
           .ToList(),
      entry.LocationLogicMode,
      terms);

    AddFormFilterTerm(
      entry.SelectedOutfitFilters
           .Select(o => FormKeyHelper.FormatForSpid(o.FormKey))
           .ToList(),
      entry.OutfitFilterLogicMode,
      terms);

    foreach (var npc in entry.SelectedNpcs.Where(n => n.IsExcluded))
    {
      exclusions.Add($"-{FormKeyHelper.FormatForSpid(npc.FormKey)}");
    }

    var result = new List<string>();
    if (terms.Count > 0)
    {
      result.AddRange(CartesianProduct(terms).Select(combo => string.Join("+", combo)));
    }

    result.AddRange(exclusions);

    if (!string.IsNullOrWhiteSpace(entry.RawFormFilters))
    {
      result.Add(entry.RawFormFilters.Trim());
    }

    return result.Count > 0 ? string.Join(",", result) : null;
  }

  internal static void AddFormFilterTerm(
    List<string> identifiers,
    FilterLogicMode logicMode,
    List<List<string>> terms)
  {
    if (identifiers.Count == 0)
    {
      return;
    }

    terms.Add(
      logicMode == FilterLogicMode.Or
        ? identifiers
        : [string.Join("+", identifiers)]);
  }

  internal static void CollectEditorIdFilters(
    IEnumerable<ISelectableRecordViewModel> items,
    FilterLogicMode logicMode,
    List<List<string>> terms,
    List<string> exclusions)
  {
    var included = new List<string>();

    foreach (var item in items)
    {
      if (string.IsNullOrWhiteSpace(item.EditorID) || item.EditorID == "(No EditorID)")
      {
        continue;
      }

      if (item.IsExcluded)
      {
        exclusions.Add($"-{item.EditorID}");
      }
      else
      {
        included.Add(item.EditorID);
      }
    }

    AddFormFilterTerm(included, logicMode, terms);
  }

  private static IEnumerable<List<string>> CartesianProduct(List<List<string>> sequences)
  {
    if (sequences.Count == 0)
    {
      yield return [];
      yield break;
    }

    if (sequences.Count == 1)
    {
      foreach (var item in sequences[0])
      {
        yield return [item];
      }

      yield break;
    }

    var first = sequences[0];
    var rest  = sequences.Skip(1).ToList();

    foreach (var item in first)
    {
      foreach (var restProduct in CartesianProduct(rest))
      {
        var result = new List<string> { item };
        result.AddRange(restProduct);
        yield return result;
      }
    }
  }

  /// <summary>
  ///   Formats a single entry as a SkyPatcher distribution line.
  ///   Format: filterByX=value:filterByY=value:outfitDefault=FormKey
  /// </summary>
  public static string FormatSkyPatcherLine(DistributionEntryViewModel entry)
  {
    if (entry.SelectedOutfit == null)
    {
      throw new ArgumentException("Entry must have a selected outfit", nameof(entry));
    }

    var filterParts = new List<string>();

    AddSkyPatcherFilterParts(
      filterParts,
      entry.SelectedNpcs,
      "filterByNpcs",
      FilterLogicMode.And);

    AddSkyPatcherFilterParts(
      filterParts,
      entry.SelectedFactions,
      "filterByFactions",
      entry.FactionLogicMode);

    AddSkyPatcherFilterParts(
      filterParts,
      entry.SelectedKeywords,
      "filterByKeywords",
      entry.KeywordLogicMode);

    AddSkyPatcherFilterParts(
      filterParts,
      entry.SelectedRaces,
      "filterByRaces",
      entry.RaceLogicMode);

    AddSkyPatcherFilterParts(
      filterParts,
      entry.SelectedClasses,
      "filterByClass",
      FilterLogicMode.And,
      "Exclude");

    if (entry.Gender != GenderFilter.Any)
    {
      var genderValue = entry.Gender == GenderFilter.Female ? "female" : "male";
      filterParts.Add($"filterByGender={genderValue}");
    }

    if (entry.Unique == UniqueFilter.UniqueOnly)
    {
      filterParts.Add("restrictToFlags=unique");
    }

    if (entry.SelectedOutfitFilters.Count > 0)
    {
      var outfitFilterKeys = entry.SelectedOutfitFilters
                                  .Select(o => FormKeyHelper.Format(o.FormKey));
      filterParts.Add($"filterByDefaultOutfits={string.Join(",", outfitFilterKeys)}");
    }

    var outfitFormKey = FormKeyHelper.Format(entry.SelectedOutfit.FormKey);
    filterParts.Add($"outfitDefault={outfitFormKey}");

    return string.Join(":", filterParts);
  }

  /// <summary>
  ///   Formats a parsed SpidDistributionFilter back to SPID syntax.
  ///   This enables round-trip testing of parsing/formatting.
  /// </summary>
  public static string FormatSpidDistributionFilter(SpidDistributionFilter filter)
  {
    if (filter.FormType == SpidFormType.ExclusiveGroup)
    {
      var forms = filter.ExclusiveGroupForms.Count > 0
                    ? string.Join(",", filter.ExclusiveGroupForms)
                    : FormatFilterSection(filter.FormFilters);

      return $"ExclusiveGroup = {filter.FormIdentifier}|{forms}";
    }

    var formTypeKeyword = filter.FormType switch
    {
      SpidFormType.Outfit         => "Outfit",
      SpidFormType.Keyword        => "Keyword",
      SpidFormType.ExclusiveGroup => "ExclusiveGroup",
      SpidFormType.Spell          => "Spell",
      SpidFormType.Perk           => "Perk",
      SpidFormType.Item           => "Item",
      SpidFormType.Shout          => "Shout",
      SpidFormType.Package        => "Package",
      SpidFormType.Faction        => "Faction",
      SpidFormType.SleepOutfit    => "SleepOutfit",
      SpidFormType.Skin           => "Skin",
      _                           => "Outfit"
    };

    var stringFiltersPart = FormatFilterSection(filter.StringFilters);
    var formFiltersPart   = FormatFilterSection(filter.FormFilters);
    var levelFiltersPart  = filter.LevelFilters;
    var traitFiltersPart  = FormatTraitFilters(filter.TraitFilters);
    var countPart         = filter.CountOrPackageIdx;
    var chancePart        = filter.Chance != 100 ? filter.Chance.ToString(CultureInfo.InvariantCulture) : null;

    var sb = new StringBuilder();
    sb.Append(formTypeKeyword);
    sb.Append(" = ");
    sb.Append(filter.FormIdentifier);

    AppendSpidFilterPositions(
      sb,
      stringFiltersPart,
      formFiltersPart,
      levelFiltersPart,
      traitFiltersPart,
      countPart,
      chancePart);

    return sb.ToString();
  }

  /// <summary>
  ///   Formats a SpidFilterSection back to SPID syntax.
  ///   Uses + for AND (within expression), , for OR (between expressions), and , for global exclusions.
  /// </summary>
  public static string? FormatFilterSection(SpidFilterSection section)
  {
    if (section.IsEmpty)
    {
      return null;
    }

    var result = new List<string>();

    foreach (var parts in section.Expressions
               .Select(expr => expr.Parts)
               .Where(p => p.Count > 0))
    {
      var formatted = parts.Select(part =>
      {
        var prefix = part.IsNegated ? "-" : string.Empty;
        return $"{prefix}{part.Value}";
      });

      result.Add(string.Join("+", formatted));
    }

    foreach (var exclusion in section.GlobalExclusions)
    {
      result.Add($"-{exclusion.Value}");
    }

    return result.Count > 0 ? string.Join(",", result) : null;
  }

  /// <summary>
  ///   Formats SPID trait filters (Position 5).
  /// </summary>
  public static string? FormatTraitFilters(SpidTraitFilters traits)
  {
    if (traits.IsEmpty)
    {
      return null;
    }

    var traitMappings = new (bool? value, string trueFlag, string falseFlag)[]
                        {
                          (traits.IsFemale, "F", "M"), (traits.IsUnique, "U", "-U"), (traits.IsSummonable, "S", "-S"),
                          (traits.IsChild, "C", "-C"), (traits.IsLeveled, "L", "-L"), (traits.IsTeammate, "T", "-T"),
                          (traits.IsDead, "D", "-D")
                        };

    var parts = traitMappings
                .Where(m => m.value.HasValue)
                .Select(m => m.value!.Value ? m.trueFlag : m.falseFlag)
                .ToList();

    return parts.Count > 0 ? string.Join("/", parts) : null;
  }

  private static void AddSkyPatcherFilterParts<T>(
    List<string> filterParts,
    IReadOnlyList<T> items,
    string baseFilterName,
    FilterLogicMode logicMode,
    string excludedSuffix = "Excluded")
    where T : ISelectableRecordViewModel
  {
    if (items.Count == 0)
    {
      return;
    }

    var included = items.Where(i => !i.IsExcluded).Select(i => FormKeyHelper.Format(i.FormKey)).ToList();
    var excluded = items.Where(i => i.IsExcluded).Select(i => FormKeyHelper.Format(i.FormKey)).ToList();

    if (included.Count > 0)
    {
      var filterName = logicMode == FilterLogicMode.Or ? $"{baseFilterName}Or" : baseFilterName;
      filterParts.Add($"{filterName}={string.Join(",", included)}");
    }

    if (excluded.Count > 0)
    {
      filterParts.Add($"{baseFilterName}{excludedSuffix}={string.Join(",", excluded)}");
    }
  }
}
