//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boutique.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutique.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} armors.
        /// </summary>
        public static string ArmorPatch_ArmorsFormat {
            get {
                return ResourceManager.GetString("ArmorPatch_ArmorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} candidates.
        /// </summary>
        public static string ArmorPatch_CandidatesFormat {
            get {
                return ResourceManager.GetString("ArmorPatch_CandidatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Patch.
        /// </summary>
        public static string ArmorPatch_CreatePatch {
            get {
                return ResourceManager.GetString("ArmorPatch_CreatePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glam-only (zero stats).
        /// </summary>
        public static string ArmorPatch_GlamOnlyZeroStats {
            get {
                return ResourceManager.GetString("ArmorPatch_GlamOnlyZeroStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Preview.
        /// </summary>
        public static string ArmorPatch_MappingPreview {
            get {
                return ResourceManager.GetString("ArmorPatch_MappingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mappings.
        /// </summary>
        public static string ArmorPatch_MappingsFormat {
            get {
                return ResourceManager.GetString("ArmorPatch_MappingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mapping(s) queued.
        /// </summary>
        public static string ArmorPatch_MappingsQueuedFormat {
            get {
                return ResourceManager.GetString("ArmorPatch_MappingsQueuedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Selection.
        /// </summary>
        public static string ArmorPatch_MapSelection {
            get {
                return ResourceManager.GetString("ArmorPatch_MapSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Glam Only.
        /// </summary>
        public static string ArmorPatch_MarkGlamOnly {
            get {
                return ResourceManager.GetString("ArmorPatch_MarkGlamOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Selection.
        /// </summary>
        public static string ArmorPatch_PluginSelection {
            get {
                return ResourceManager.GetString("ArmorPatch_PluginSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove mapping.
        /// </summary>
        public static string ArmorPatch_RemoveMapping {
            get {
                return ResourceManager.GetString("ArmorPatch_RemoveMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Armors.
        /// </summary>
        public static string ArmorPatch_SourceArmors {
            get {
                return ResourceManager.GetString("ArmorPatch_SourceArmors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Plugin.
        /// </summary>
        public static string ArmorPatch_SourcePlugin {
            get {
                return ResourceManager.GetString("ArmorPatch_SourcePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Armors.
        /// </summary>
        public static string ArmorPatch_TargetArmors {
            get {
                return ResourceManager.GetString("ArmorPatch_TargetArmors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Plugin.
        /// </summary>
        public static string ArmorPatch_TargetPlugin {
            get {
                return ResourceManager.GetString("ArmorPatch_TargetPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total mappings.
        /// </summary>
        public static string ArmorPatch_TotalMappingsFormat {
            get {
                return ResourceManager.GetString("ArmorPatch_TotalMappingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search plugins.
        /// </summary>
        public static string ArmorPatch_TypeToSearch {
            get {
                return ResourceManager.GetString("ArmorPatch_TypeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Detect.
        /// </summary>
        public static string Button_AutoDetect {
            get {
                return ResourceManager.GetString("Button_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Button_ClearAll {
            get {
                return ResourceManager.GetString("Button_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string Button_ClearFilters {
            get {
                return ResourceManager.GetString("Button_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↻ Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset View.
        /// </summary>
        public static string Button_ResetView {
            get {
                return ResourceManager.GetString("Button_ResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Tutorial.
        /// </summary>
        public static string Button_RestartTutorial {
            get {
                return ResourceManager.GetString("Button_RestartTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detection failed for {0} - please set manually.
        /// </summary>
        public static string Detection_Failed {
            get {
                return ResourceManager.GetString("Detection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected from Mod Organizer 2 (MO_DATAPATH).
        /// </summary>
        public static string Detection_MO2DataPath {
            get {
                return ResourceManager.GetString("Detection_MO2DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected from Mod Organizer 2 (MO_GAMEPATH).
        /// </summary>
        public static string Detection_MO2GamePath {
            get {
                return ResourceManager.GetString("Detection_MO2GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running under Mod Organizer 2 USVFS (data path not explicitly set).
        /// </summary>
        public static string Detection_MO2USVFS {
            get {
                return ResourceManager.GetString("Detection_MO2USVFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected from Mod Organizer 2 (VIRTUAL_STORE).
        /// </summary>
        public static string Detection_MO2VirtualStore {
            get {
                return ResourceManager.GetString("Detection_MO2VirtualStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected {0} using Mutagen.
        /// </summary>
        public static string Detection_Mutagen {
            get {
                return ResourceManager.GetString("Detection_Mutagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Skyrim Data Folder.
        /// </summary>
        public static string Dialog_SelectDataFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distribution File Location.
        /// </summary>
        public static string Dialog_SelectDistributionFile {
            get {
                return ResourceManager.GetString("Dialog_SelectDistributionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder for Patch.
        /// </summary>
        public static string Dialog_SelectOutputFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry.
        /// </summary>
        public static string Distribution_AddEntry {
            get {
                return ResourceManager.GetString("Distribution_AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected Classes to Entry.
        /// </summary>
        public static string Distribution_AddSelectedClasses {
            get {
                return ResourceManager.GetString("Distribution_AddSelectedClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected Factions to Entry.
        /// </summary>
        public static string Distribution_AddSelectedFactions {
            get {
                return ResourceManager.GetString("Distribution_AddSelectedFactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected Keywords to Entry.
        /// </summary>
        public static string Distribution_AddSelectedKeywords {
            get {
                return ResourceManager.GetString("Distribution_AddSelectedKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected NPCs to Entry.
        /// </summary>
        public static string Distribution_AddSelectedNpcs {
            get {
                return ResourceManager.GetString("Distribution_AddSelectedNpcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected Races to Entry.
        /// </summary>
        public static string Distribution_AddSelectedRaces {
            get {
                return ResourceManager.GetString("Distribution_AddSelectedRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Distribution_Assign {
            get {
                return ResourceManager.GetString("Distribution_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance (0-100).
        /// </summary>
        public static string Distribution_ChanceTooltip {
            get {
                return ResourceManager.GetString("Distribution_ChanceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes:.
        /// </summary>
        public static string Distribution_Classes {
            get {
                return ResourceManager.GetString("Distribution_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Entries.
        /// </summary>
        public static string Distribution_DistributionEntries {
            get {
                return ResourceManager.GetString("Distribution_DistributionEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Filters.
        /// </summary>
        public static string Distribution_DistributionFilters {
            get {
                return ResourceManager.GetString("Distribution_DistributionFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions:.
        /// </summary>
        public static string Distribution_Factions {
            get {
                return ResourceManager.GetString("Distribution_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Preview.
        /// </summary>
        public static string Distribution_FilePreview {
            get {
                return ResourceManager.GetString("Distribution_FilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string Distribution_Gender {
            get {
                return ResourceManager.GetString("Distribution_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword:.
        /// </summary>
        public static string Distribution_Keyword {
            get {
                return ResourceManager.GetString("Distribution_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords:.
        /// </summary>
        public static string Distribution_Keywords {
            get {
                return ResourceManager.GetString("Distribution_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level/Skill:.
        /// </summary>
        public static string Distribution_LevelSkill {
            get {
                return ResourceManager.GetString("Distribution_LevelSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPID level/skill filters. Examples: 5/20 (level range), 12(85/999) (Alteration skill 85+).
        /// </summary>
        public static string Distribution_LevelSkillTooltip {
            get {
                return ResourceManager.GetString("Distribution_LevelSkillTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPCs:.
        /// </summary>
        public static string Distribution_NPCs {
            get {
                return ResourceManager.GetString("Distribution_NPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit:.
        /// </summary>
        public static string Distribution_Outfit {
            get {
                return ResourceManager.GetString("Distribution_Outfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parsing error(s) - these lines will be preserved on save.
        /// </summary>
        public static string Distribution_ParseErrorsFormat {
            get {
                return ResourceManager.GetString("Distribution_ParseErrorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Paste Filter.
        /// </summary>
        public static string Distribution_PasteFilter {
            get {
                return ResourceManager.GetString("Distribution_PasteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste filter: {0}.
        /// </summary>
        public static string Distribution_PasteFilterFormat {
            get {
                return ResourceManager.GetString("Distribution_PasteFilterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste copied filter from NPCs tab.
        /// </summary>
        public static string Distribution_PasteFilterTooltip {
            get {
                return ResourceManager.GetString("Distribution_PasteFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races:.
        /// </summary>
        public static string Distribution_Races {
            get {
                return ResourceManager.GetString("Distribution_Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Entry.
        /// </summary>
        public static string Distribution_RemoveEntry {
            get {
                return ResourceManager.GetString("Distribution_RemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string Distribution_SaveFile {
            get {
                return ResourceManager.GetString("Distribution_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing keyword or type a new EditorID for virtual keywords.
        /// </summary>
        public static string Distribution_SelectKeywordTooltip {
            get {
                return ResourceManager.GetString("Distribution_SelectKeywordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Entry: {0}.
        /// </summary>
        public static string Distribution_TargetEntryFormat {
            get {
                return ResourceManager.GetString("Distribution_TargetEntryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Entry: (None selected).
        /// </summary>
        public static string Distribution_TargetEntryNone {
            get {
                return ResourceManager.GetString("Distribution_TargetEntryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits:.
        /// </summary>
        public static string Distribution_Traits {
            get {
                return ResourceManager.GetString("Distribution_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique:.
        /// </summary>
        public static string Distribution_Unique {
            get {
                return ResourceManager.GetString("Distribution_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Chance.
        /// </summary>
        public static string Distribution_UseChance {
            get {
                return ResourceManager.GetString("Distribution_UseChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by child/adult status (SPID trait: C/-C).
        /// </summary>
        public static string Filter_ChildTooltip {
            get {
                return ResourceManager.GetString("Filter_ChildTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by NPC class (SPID FormFilter).
        /// </summary>
        public static string Filter_ClassTooltip {
            get {
                return ResourceManager.GetString("Filter_ClassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by faction membership (SPID FormFilter).
        /// </summary>
        public static string Filter_FactionTooltip {
            get {
                return ResourceManager.GetString("Filter_FactionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by NPC gender (SPID trait: F/M).
        /// </summary>
        public static string Filter_GenderTooltip {
            get {
                return ResourceManager.GetString("Filter_GenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by keyword (SPID StringFilter).
        /// </summary>
        public static string Filter_KeywordTooltip {
            get {
                return ResourceManager.GetString("Filter_KeywordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by race (SPID FormFilter).
        /// </summary>
        public static string Filter_RaceTooltip {
            get {
                return ResourceManager.GetString("Filter_RaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filters to default.
        /// </summary>
        public static string Filter_ResetTooltip {
            get {
                return ResourceManager.GetString("Filter_ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by whether NPC uses a template.
        /// </summary>
        public static string Filter_TemplatedTooltip {
            get {
                return ResourceManager.GetString("Filter_TemplatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by unique NPC flag (SPID trait: U/-U).
        /// </summary>
        public static string Filter_UniqueTooltip {
            get {
                return ResourceManager.GetString("Filter_UniqueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Header_Armor {
            get {
                return ResourceManager.GetString("Header_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string Header_Chance {
            get {
                return ResourceManager.GetString("Header_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string Header_Conflict {
            get {
                return ResourceManager.GetString("Header_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Header_Copy {
            get {
                return ResourceManager.GetString("Header_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Header_Distributor {
            get {
                return ResourceManager.GetString("Header_Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorID.
        /// </summary>
        public static string Header_EditorID {
            get {
                return ResourceManager.GetString("Header_EditorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Outfit.
        /// </summary>
        public static string Header_FinalOutfit {
            get {
                return ResourceManager.GetString("Header_FinalOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form ID.
        /// </summary>
        public static string Header_FormID {
            get {
                return ResourceManager.GetString("Header_FormID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormKey.
        /// </summary>
        public static string Header_FormKey {
            get {
                return ResourceManager.GetString("Header_FormKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Header_Mod {
            get {
                return ResourceManager.GetString("Header_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPCs.
        /// </summary>
        public static string Header_NPCs {
            get {
                return ResourceManager.GetString("Header_NPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Header_Override {
            get {
                return ResourceManager.GetString("Header_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Header_Preview {
            get {
                return ResourceManager.GetString("Header_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string Header_Slots {
            get {
                return ResourceManager.GetString("Header_Slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting.
        /// </summary>
        public static string Header_Targeting {
            get {
                return ResourceManager.GetString("Header_Targeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Header_Type {
            get {
                return ResourceManager.GetString("Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename:.
        /// </summary>
        public static string Label_Filename {
            get {
                return ResourceManager.GetString("Label_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Filter....
        /// </summary>
        public static string Label_FilterPlaceholder {
            get {
                return ResourceManager.GetString("Label_FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Label_Format {
            get {
                return ResourceManager.GetString("Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves as:.
        /// </summary>
        public static string Label_SavesAs {
            get {
                return ResourceManager.GetString("Label_SavesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested:.
        /// </summary>
        public static string Label_Suggested {
            get {
                return ResourceManager.GetString("Label_Suggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll add the master(s) back.
        /// </summary>
        public static string MissingMasters_AddBack {
            get {
                return ResourceManager.GetString("MissingMasters_AddBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean patch (remove outfits).
        /// </summary>
        public static string MissingMasters_CleanPatch {
            get {
                return ResourceManager.GetString("MissingMasters_CleanPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BoutiquePatch references plugins that are no longer in your load order. The outfits below contain armor from these missing masters and cannot be loaded..
        /// </summary>
        public static string MissingMasters_Description {
            get {
                return ResourceManager.GetString("MissingMasters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Missing Master Plugins Detected.
        /// </summary>
        public static string MissingMasters_Header {
            get {
                return ResourceManager.GetString("MissingMasters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} orphaned armor(s)).
        /// </summary>
        public static string MissingMasters_OrphanedFormat {
            get {
                return ResourceManager.GetString("MissingMasters_OrphanedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Masters Detected.
        /// </summary>
        public static string MissingMasters_Title {
            get {
                return ResourceManager.GetString("MissingMasters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string NPCs_Age {
            get {
                return ResourceManager.GetString("NPCs_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}% chance).
        /// </summary>
        public static string NPCs_ChanceFormat {
            get {
                return ResourceManager.GetString("NPCs_ChanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        public static string NPCs_Class {
            get {
                return ResourceManager.GetString("NPCs_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat:.
        /// </summary>
        public static string NPCs_Combat {
            get {
                return ResourceManager.GetString("NPCs_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Copy Filter.
        /// </summary>
        public static string NPCs_CopyFilter {
            get {
                return ResourceManager.GetString("NPCs_CopyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current filter to paste in Create tab.
        /// </summary>
        public static string NPCs_CopyFilterTooltip {
            get {
                return ResourceManager.GetString("NPCs_CopyFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy syntax to use in your distribution INI files.
        /// </summary>
        public static string NPCs_CopySyntaxHint {
            get {
                return ResourceManager.GetString("NPCs_CopySyntaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Files.
        /// </summary>
        public static string NPCs_DistributionFiles {
            get {
                return ResourceManager.GetString("NPCs_DistributionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction:.
        /// </summary>
        public static string NPCs_Faction {
            get {
                return ResourceManager.GetString("NPCs_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string NPCs_Female {
            get {
                return ResourceManager.GetString("NPCs_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Syntax Preview.
        /// </summary>
        public static string NPCs_FilterSyntaxPreview {
            get {
                return ResourceManager.GetString("NPCs_FilterSyntaxPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide vanilla distributions.
        /// </summary>
        public static string NPCs_HideVanilla {
            get {
                return ResourceManager.GetString("NPCs_HideVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides NPCs with their default outfit as the winning assignment.
        /// </summary>
        public static string NPCs_HideVanillaTooltip {
            get {
                return ResourceManager.GetString("NPCs_HideVanillaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string NPCs_Level {
            get {
                return ResourceManager.GetString("NPCs_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string NPCs_Male {
            get {
                return ResourceManager.GetString("NPCs_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Details.
        /// </summary>
        public static string NPCs_NpcDetails {
            get {
                return ResourceManager.GetString("NPCs_NpcDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit Contents.
        /// </summary>
        public static string NPCs_OutfitContents {
            get {
                return ResourceManager.GetString("NPCs_OutfitContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit: {0}.
        /// </summary>
        public static string NPCs_OutfitFormat {
            get {
                return ResourceManager.GetString("NPCs_OutfitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Outfit.
        /// </summary>
        public static string NPCs_PreviewOutfit {
            get {
                return ResourceManager.GetString("NPCs_PreviewOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race:.
        /// </summary>
        public static string NPCs_Race {
            get {
                return ResourceManager.GetString("NPCs_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Rank {0}).
        /// </summary>
        public static string NPCs_RankFormat {
            get {
                return ResourceManager.GetString("NPCs_RankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan distribution files for NPC outfit assignments.
        /// </summary>
        public static string NPCs_RefreshTooltip {
            get {
                return ResourceManager.GetString("NPCs_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search NPCs by name, EditorID, outfit, or mod.
        /// </summary>
        public static string NPCs_SearchTooltip {
            get {
                return ResourceManager.GetString("NPCs_SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} of {1} NPCs.
        /// </summary>
        public static string NPCs_ShowingFormat {
            get {
                return ResourceManager.GetString("NPCs_ShowingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyPatcher Format:.
        /// </summary>
        public static string NPCs_SkyPatcherFormat {
            get {
                return ResourceManager.GetString("NPCs_SkyPatcherFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPID-Style Filters.
        /// </summary>
        public static string NPCs_SpidFilters {
            get {
                return ResourceManager.GetString("NPCs_SpidFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPID Format:.
        /// </summary>
        public static string NPCs_SpidFormat {
            get {
                return ResourceManager.GetString("NPCs_SpidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template:.
        /// </summary>
        public static string NPCs_Template {
            get {
                return ResourceManager.GetString("NPCs_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templated:.
        /// </summary>
        public static string NPCs_Templated {
            get {
                return ResourceManager.GetString("NPCs_Templated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string NPCs_TemplateNone {
            get {
                return ResourceManager.GetString("NPCs_TemplateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string NPCs_Trait_Child {
            get {
                return ResourceManager.GetString("NPCs_Trait_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveled.
        /// </summary>
        public static string NPCs_Trait_Leveled {
            get {
                return ResourceManager.GetString("NPCs_Trait_Leveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summonable.
        /// </summary>
        public static string NPCs_Trait_Summonable {
            get {
                return ResourceManager.GetString("NPCs_Trait_Summonable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string NPCs_Trait_Unique {
            get {
                return ResourceManager.GetString("NPCs_Trait_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice:.
        /// </summary>
        public static string NPCs_Voice {
            get {
                return ResourceManager.GetString("NPCs_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WINNER].
        /// </summary>
        public static string NPCs_Winner {
            get {
                return ResourceManager.GetString("NPCs_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Armors.
        /// </summary>
        public static string OutfitCreator_AvailableArmors {
            get {
                return ResourceManager.GetString("OutfitCreator_AvailableArmors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Existing Outfits.
        /// </summary>
        public static string OutfitCreator_CopyExistingOutfits {
            get {
                return ResourceManager.GetString("OutfitCreator_CopyExistingOutfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Outfit from Selected.
        /// </summary>
        public static string OutfitCreator_CreateNewOutfit {
            get {
                return ResourceManager.GetString("OutfitCreator_CreateNewOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop armors here to create a new outfit (double-click an armor to quick add)..
        /// </summary>
        public static string OutfitCreator_DropArmorsHere {
            get {
                return ResourceManager.GetString("OutfitCreator_DropArmorsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Outfit.
        /// </summary>
        public static string OutfitCreator_DuplicateOutfit {
            get {
                return ResourceManager.GetString("OutfitCreator_DuplicateOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin already defines {0} outfit(s)..
        /// </summary>
        public static string OutfitCreator_ExistingOutfitsFormat {
            get {
                return ResourceManager.GetString("OutfitCreator_ExistingOutfitsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter plugins by name.
        /// </summary>
        public static string OutfitCreator_FilterPlugins {
            get {
                return ResourceManager.GetString("OutfitCreator_FilterPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No outfits created yet. Select armors and click Create Outfit..
        /// </summary>
        public static string OutfitCreator_NoOutfitsQueued {
            get {
                return ResourceManager.GetString("OutfitCreator_NoOutfitsQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pieces selected..
        /// </summary>
        public static string OutfitCreator_NoPiecesSelected {
            get {
                return ResourceManager.GetString("OutfitCreator_NoPiecesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutique Outfits.
        /// </summary>
        public static string OutfitCreator_OutfitQueue {
            get {
                return ResourceManager.GetString("OutfitCreator_OutfitQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} outfit(s).
        /// </summary>
        public static string OutfitCreator_OutfitsQueuedFormat {
            get {
                return ResourceManager.GetString("OutfitCreator_OutfitsQueuedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview armor.
        /// </summary>
        public static string OutfitCreator_PreviewArmor {
            get {
                return ResourceManager.GetString("OutfitCreator_PreviewArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Outfit.
        /// </summary>
        public static string OutfitCreator_PreviewOutfit {
            get {
                return ResourceManager.GetString("OutfitCreator_PreviewOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Outfit.
        /// </summary>
        public static string OutfitCreator_RemoveOutfit {
            get {
                return ResourceManager.GetString("OutfitCreator_RemoveOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove piece.
        /// </summary>
        public static string OutfitCreator_RemovePiece {
            get {
                return ResourceManager.GetString("OutfitCreator_RemovePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Outfits.
        /// </summary>
        public static string OutfitCreator_SaveOutfits {
            get {
                return ResourceManager.GetString("OutfitCreator_SaveOutfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Plugins.
        /// </summary>
        public static string OutfitCreator_SourcePlugins {
            get {
                return ResourceManager.GetString("OutfitCreator_SourcePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Override.
        /// </summary>
        public static string Outfits_CopyAsOverride {
            get {
                return ResourceManager.GetString("Outfits_CopyAsOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Patch.
        /// </summary>
        public static string Outfits_CopyToPatch {
            get {
                return ResourceManager.GetString("Outfits_CopyToPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed to NPCs.
        /// </summary>
        public static string Outfits_DistributedToNpcs {
            get {
                return ResourceManager.GetString("Outfits_DistributedToNpcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides Outfits with their default outfit as the winning assignment.
        /// </summary>
        public static string Outfits_HideVanillaTooltip {
            get {
                return ResourceManager.GetString("Outfits_HideVanillaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↻ Load Outfits.
        /// </summary>
        public static string Outfits_LoadOutfits {
            get {
                return ResourceManager.GetString("Outfits_LoadOutfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all outfits from the load order.
        /// </summary>
        public static string Outfits_LoadTooltip {
            get {
                return ResourceManager.GetString("Outfits_LoadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search outfits by EditorID, FormKey, or mod.
        /// </summary>
        public static string Outfits_SearchTooltip {
            get {
                return ResourceManager.GetString("Outfits_SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ This name conflicts with an existing plugin.
        /// </summary>
        public static string PatchNameCollision_Header {
            get {
                return ResourceManager.GetString("PatchNameCollision_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep This Name.
        /// </summary>
        public static string PatchNameCollision_KeepName {
            get {
                return ResourceManager.GetString("PatchNameCollision_KeepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; already exists in your load order. Using this name may overwrite existing data when you create a patch. Consider choosing a unique name..
        /// </summary>
        public static string PatchNameCollision_Message {
            get {
                return ResourceManager.GetString("PatchNameCollision_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Different Name.
        /// </summary>
        public static string PatchNameCollision_Revert {
            get {
                return ResourceManager.GetString("PatchNameCollision_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Name Conflict.
        /// </summary>
        public static string PatchNameCollision_Title {
            get {
                return ResourceManager.GetString("PatchNameCollision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string Preview_Ambient {
            get {
                return ResourceManager.GetString("Preview_Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some creators like [ELLE] make their outfits such that you have to run BodySlide with the outfit before it&apos;s fully usable. If this sounds like it might be the case, quit Boutique and do all the requisite BodySlide steps, then get back here and try again!.
        /// </summary>
        public static string Preview_BodySlideHint {
            get {
                return ResourceManager.GetString("Preview_BodySlideHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontal.
        /// </summary>
        public static string Preview_Frontal {
            get {
                return ResourceManager.GetString("Preview_Frontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Fill.
        /// </summary>
        public static string Preview_KeyFill {
            get {
                return ResourceManager.GetString("Preview_KeyFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting multipliers (Debug).
        /// </summary>
        public static string Preview_LightingDebug {
            get {
                return ResourceManager.GetString("Preview_LightingDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assets:.
        /// </summary>
        public static string Preview_MissingAssets {
            get {
                return ResourceManager.GetString("Preview_MissingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some assets were missing when previewing this outfit..
        /// </summary>
        public static string Preview_MissingAssetsWarning {
            get {
                return ResourceManager.GetString("Preview_MissingAssetsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rim.
        /// </summary>
        public static string Preview_Rim {
            get {
                return ResourceManager.GetString("Preview_Rim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit Preview.
        /// </summary>
        public static string Preview_Title {
            get {
                return ResourceManager.GetString("Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh All Data (including output patch).
        /// </summary>
        public static string Refresh_Tooltip {
            get {
                return ResourceManager.GetString("Refresh_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll do it later!.
        /// </summary>
        public static string Restart_Later {
            get {
                return ResourceManager.GetString("Restart_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the color scheme change, you need to quit and reopen Boutique..
        /// </summary>
        public static string Restart_Message {
            get {
                return ResourceManager.GetString("Restart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Now.
        /// </summary>
        public static string Restart_QuitNow {
            get {
                return ResourceManager.GetString("Restart_QuitNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string Restart_Title {
            get {
                return ResourceManager.GetString("Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist:.
        /// </summary>
        public static string Settings_Blacklist {
            get {
                return ResourceManager.GetString("Settings_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection:.
        /// </summary>
        public static string Settings_Detection {
            get {
                return ResourceManager.GetString("Settings_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Settings_Group_Advanced {
            get {
                return ResourceManager.GetString("Settings_Group_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Group_Appearance {
            get {
                return ResourceManager.GetString("Settings_Group_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Configuration.
        /// </summary>
        public static string Settings_Group_GameConfiguration {
            get {
                return ResourceManager.GetString("Settings_Group_GameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Settings.
        /// </summary>
        public static string Settings_Group_PatchSettings {
            get {
                return ResourceManager.GetString("Settings_Group_PatchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path:.
        /// </summary>
        public static string Settings_OutputPath {
            get {
                return ResourceManager.GetString("Settings_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty to use Skyrim Data path. Set a custom path for Wabbajack modlists or MO2 overwrite folder..
        /// </summary>
        public static string Settings_OutputPathTooltip {
            get {
                return ResourceManager.GetString("Settings_OutputPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch File Name:.
        /// </summary>
        public static string Settings_PatchFileName {
            get {
                return ResourceManager.GetString("Settings_PatchFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim Data Path:.
        /// </summary>
        public static string Settings_SkyrimDataPath {
            get {
                return ResourceManager.GetString("Settings_SkyrimDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim Release:.
        /// </summary>
        public static string Settings_SkyrimRelease {
            get {
                return ResourceManager.GetString("Settings_SkyrimRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial:.
        /// </summary>
        public static string Settings_Tutorial {
            get {
                return ResourceManager.GetString("Settings_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim SE (GOG).
        /// </summary>
        public static string SkyrimRelease_GOG {
            get {
                return ResourceManager.GetString("SkyrimRelease_GOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim SE.
        /// </summary>
        public static string SkyrimRelease_SE {
            get {
                return ResourceManager.GetString("SkyrimRelease_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim VR.
        /// </summary>
        public static string SkyrimRelease_VR {
            get {
                return ResourceManager.GetString("SkyrimRelease_VR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Status_Initializing {
            get {
                return ResourceManager.GetString("Status_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch:.
        /// </summary>
        public static string Status_Patch {
            get {
                return ResourceManager.GetString("Status_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Patch.
        /// </summary>
        public static string Tab_ArmorPatch {
            get {
                return ResourceManager.GetString("Tab_ArmorPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Tab_Classes {
            get {
                return ResourceManager.GetString("Tab_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string Tab_Containers {
            get {
                return ResourceManager.GetString("Tab_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Tab_Create {
            get {
                return ResourceManager.GetString("Tab_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string Tab_Distribution {
            get {
                return ResourceManager.GetString("Tab_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions.
        /// </summary>
        public static string Tab_Factions {
            get {
                return ResourceManager.GetString("Tab_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Tab_Keywords {
            get {
                return ResourceManager.GetString("Tab_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPCs.
        /// </summary>
        public static string Tab_NPCs {
            get {
                return ResourceManager.GetString("Tab_NPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit Creator.
        /// </summary>
        public static string Tab_OutfitCreator {
            get {
                return ResourceManager.GetString("Tab_OutfitCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfits.
        /// </summary>
        public static string Tab_Outfits {
            get {
                return ResourceManager.GetString("Tab_Outfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string Tab_Races {
            get {
                return ResourceManager.GetString("Tab_Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
    }
}
